### DISCUSSION TITLE
Documentation update request: Health Check endpoint

### DISCUSSION THREAD

**Discussion by userbradley** [shlinkio/shlink#1816] [Show and tell]
I am deploying shlink in GKE, and it's best practice to use a healthcheck.

I was not able to find on listed in the documentation, but was able to find the below endpoint 

`/rest/health`

in an issue: https://github.com/shlinkio/shlink/issues/367

Please can both of the below be done:

- [x] Mention this in the documentation 
- [x] Continue being super cool

If you dont have the time, but know where this should go, I can look to open a PR

thanks

-Brad

**Comment by acelaya** [comment]
Haha. I guess I could try to improve on the second 😅

As per the first, it's part of the API spec docs https://api-spec.shlink.io/#/Monitoring/health, but I guess that's not where you would look for it first.

I have created this https://github.com/shlinkio/shlink.io/issues/354

**Comment by webysther** [comment]
For who get here and wait just a sample:

```yml
version: "3.9"
services:
  shlink:
    image: shlinkio/shlink-web-client:3.10.1
    container_name: app-shlink
    env_file: ../shlink/.env
    networks:
      shlink:
    healthcheck:
      test: curl --fail http://localhost || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    expose:
      - 80
    depends_on:
      shlink-api:
        condition: service_healthy
    restart: unless-stopped

  shlink-api:
    image: shlinkio/shlink:3.6.3
    container_name: app-shlink-api
    env_file: ../shlink/.env
    networks:
      shlink-backend:
      shlink:
    healthcheck:
      test: curl --fail http://localhost:8080/rest/health || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    expose:
      - 8080
    depends_on:
      shlink-db:
        condition: service_healthy
    restart: unless-stopped

  shlink-db:
    image: postgres:15
    container_name: db-postgres-shlink
    env_file: ../shlink/.env
    user: "${PUID}:${PGID}"
    networks:
      shlink-backend:
    volumes:
      - "$STORAGE/db:/var/lib/postgresql/data"
    expose:
      - 5432
    healthcheck:
      test: [
        "CMD-SHELL", 
        "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"
      ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

networks:
  shlink-backend:
    name: shlink-backend
  shlink:
    name: shlink
```
