### DISCUSSION TITLE
does this docker-compose.yml work？

### DISCUSSION THREAD

**Discussion by johnsmithodom** [shlinkio/shlink#1831] [Help wanted] [answered]
Got logs
root@vps:~/shlink# docker-compose up -d &
[+] Running 3/3~/shlink#
 ✔ Network shlink_default  Created                                                     0.1s
 ✔ Container mysql         Started                                                     2.5s
 ✔ Container my_shlink     Started                                                     9.3s
 
```
version: '3.8'

services:
  shlink:
    image: shlinkio/shlink:stable
    container_name: my_shlink
    ports:
      - 8080:8080
    environment:
      - DEFAULT_DOMAIN=www.mydomain.tld
      - IS_HTTPS_ENABLED=true
      - GEOLITE_LICENSE_KEY=kjh23ljkbn11111111111111dskj345
      - DB_DRIVER=mysql
      - DB_USER=shlink_user
      - DB_PASSWORD=shlink_password
      - DB_HOST=mysql
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=shlink
      - MYSQL_USER=shlink_user
      - MYSQL_PASSWORD=shlink_password
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:


```

visiting www.mydomain.tld  and have A record pointing to my vps public ip,  nothing shows up.
