### DISCUSSION TITLE
Help: Oops! We could not find requested route.

### DISCUSSION THREAD

**Discussion by Caesarovich** [shlinkio/shlink#1946] [Help wanted] [answered]
### Shlink version

v3.7.0

### PHP version

container

### How do you serve Shlink

RoadRunner Docker image

### Database engine

SQLite

### Database version

0.0.0

### Summary

Hi, I'm trying to setup shlink with Docker compose like so:

```yml
    restarted: true
    project_name: shlink
    pull: true
    definition:
      version: '3'
      services:
        server:
          restart: unless-stopped
          image: shlinkio/shlink:stable
          volumes:
            - '/etc/shlink/data'
          environment:
            DEFAULT_DOMAIN: 's.XXX'
            IS_HTTPS_ENABLED: 1
          ports:
            - 'XXXX:8080'
```

I can connect to the web interface at s.XXXX, I create a shortened URL but when I click it the following error appears:

> Oops! We could not find requested route.
>
> Use your browser's back button to navigate to the page you have previously come from, or just press this button.

I'm not sure what the issue is but I think it's trying to find the shortened URL on the web client instead of redirecting to its original URL ?
