### DISCUSSION TITLE
Help wanted, docker compose setup, unable to link to server.

### DISCUSSION THREAD

**Discussion by Today20092** [shlinkio/shlink#1977] [Help wanted] [answered]
### Shlink version

3.73

### PHP version

unsure

### How do you serve Shlink

Other (explain in summary)

### Database engine

MariaDB

### Database version

10.8

### Summary

I am having issues setting up this shlink setup from [this youtube video](https://youtu.be/X8HrJZTYOQU).
**Any help with fixing this will be greatly appreciated and a good learning experience for me.**

This is my current setup:

![image](https://github.com/shlinkio/shlink/assets/79241611/63f94c56-b83b-4a86-b922-7a01ca7e9cb9)
_The docker containers are running inside of a proxmox lxc container with its own IP address.
I also have another lxc container running nginx proxy manager and i did make a proxy host pointing to the port 8081 of the ip address of the proxmox lxc container that has docker.
I do have an ssl certificate to my domain with nginx proxy manager._

Currently i am able to access the gui, but not able to link the server.

This person seems to have a similar setup except with traefik, but i wasnt' able to get anything useful out of it.
#1958 

![image](https://github.com/shlinkio/shlink/assets/79241611/af63bb4d-7e49-4863-b14b-f360674c4cc8)

this is my docker compose:
```yaml
version: "3"

services:
  shlink:
    image: shlinkio/shlink:stable
    restart: always
    container_name: shlink-backend
    environment:
      - TZ="America/New_York"
      - DEFAULT_DOMAIN=link.domain.xyz #no http/https. no trailing slash
      - IS_HTTPS_ENABLED=true
      - GEOLITE_LICENSE_KEY=abcdef #we'll need to get this key from maxmind.com
      - DB_DRIVER=maria
      - DB_USER=shlink
      - DB_NAME=shlink
      - DB_PASSWORD=password #change this
      - DB_HOST=database
    depends_on:
      - database
    ports:
      - 8987:8080

  database:
    image: mariadb:10.8
    restart: always
    container_name: shlink-database
    environment:
      - MARIADB_ROOT_PASSWORD=password #change this
      - MARIADB_DATABASE=shlink
      - MARIADB_USER=shlink
      - MARIADB_PASSWORD=password #change this
    volumes:
      - /home/docker/shlink/db:/var/lib/mysql

  shlink-web-client:
    image: shlinkio/shlink-web-client
    restart: always
    container_name: shlink-gui
    volumes:
      - /home/docker/shlink/servers.json:/usr/share/nginx/html/servers.json #this file will be generated automatically
    depends_on:
      - shlink
    ports:
      - 8081:80
```
