### DISCUSSION TITLE
Visited URL only showing localhost

### DISCUSSION THREAD

**Discussion by Jisagi** [shlinkio/shlink#2171] [Help wanted]
### Shlink version

4.1.1

### PHP version

-

### How do you serve Shlink

Docker image

### Database engine

PostgreSQL

### Database version

16.3

### Summary

Hi, I am running shlink as a selfhosted instance with a postrgres db and the web-client, all of them inside their own docker and in the same network. All basic functions I tested so far have been working just fine. The only thing I did not get to work is the "Visited URL" column in the visit statistics. Every visit only lists `http://127.0.0.1:8085/some-test-slug`. The locations ont he other hand do work just fine, so he is ablet o determine the calling ip, but somehow uses the wrong host.

It only shows the docker host of the shlink service and hot the actual host it was called from. I also tried `SERVER_NAME` for the `Host` ReqHeader, but no luck either. It does feel like shlink does not use the Host Header at all, or the reverse proxy config is incorrect in some other way.

compose file
```
services:
  shlink:
    image: shlinkio/shlink:stable
    container_name: shlink
    restart: unless-stopped
    environment:
      - DEFAULT_DOMAIN=sub.domain.tld
      - IS_HTTPS_ENABLED=true
      - GEOLITE_LICENSE_KEY=<KEY>
      - DB_DRIVER=postgres
      - DB_USER=shlink-database-user
      - DB_PASSWORD=<PASSWORD>
      - DB_HOST=shlink-db
    ports:
      - 127.0.0.1:8085:8080
    depends_on:
      - shlink-db

  shlink-db:
    image: postgres:16
    container_name: shlink-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=shlink-database-user
      - POSTGRES_PASSWORD=<PASSWORD>
      - POSTGRES_DB=shlink
    volumes:
      - /<LOCAL_PATH>/shlink-db:/var/lib/postgresql/data

[web-config ...]
```

apache2 config
```
<VirtualHost *:443>
    ServerName sub.domain.tld

    SSLEngine on
    SSLCertificateFile  /<LOCAL_PATH>/fullchain.pem
    SSLCertificateKeyFile /<LOCAL_PATH>/privkey.pem

    ProxyPass / http://127.0.0.1:8085/
    ProxyPassReverse / http://127.0.0.1:8085/

    RequestHeader set Host %{HTTP_HOST}s
    RequestHeader set X-Real-IP %{REMOTE_ADDR}s
    RequestHeader set X-Forwarded-For "%{X-Forwarded-For}s
    RequestHeader set X-Forwarded-Proto "https"
</VirtualHost>
```
