### DISCUSSION TITLE
Help with coolify and shlink installation

### DISCUSSION THREAD

**Discussion by mredodos** [shlinkio/shlink#2259] [Help wanted] [answered]
### Shlink version

stable

### PHP version

last

### How do you serve Shlink

Docker image

### Database engine

SQLite

### Database version

last

### Summary

Hi, I need help configuring and running shlink with coolify!

can anyone help me?

**Comment by acelaya** [comment]
Hi. 

It's going to be hard for anyone to help you if you don't provide more details.

* What is coolify? (Documentation links, explanations, etc.)
* What have you tried so far, steps you followed, what parts of the documentation you used, etc. 
* What errors have you faced, what became a stopper that motivated you to open this help request.

The more details you can provide, the more likely it is that someone from the community has faced something similar or has experience with that and can help.

Too broad and generic questions are likely just going to be ignored by everyone.

**Comment by mredodos** [comment]
This is https://coolify.io/ and via coolify we can add in onecli shlink https://coolify.io/docs/services/shlink/

This is the error 

![image](https://github.com/user-attachments/assets/543a5f0b-52c1-40c3-bfef-6f4965ae888f)

this is the docker compose, coolify automatically handles the traefik labels

```
services:
  shlink:
    image: 'shlinkio/shlink:stable'
    environment:
      - SERVICE_FQDN_SHLINK_8080
      - 'DEFAULT_DOMAIN=${SERVICE_URL_SHLINK}'
      - IS_HTTPS_ENABLED=false
      - 'INITIAL_API_KEY=${SERVICE_BASE64_SHLINKAPIKEY}'
    volumes:
      - 'shlink-data:/etc/shlink/data'
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://127.0.0.1:8080/rest/v3/health'
      interval: 2s
      timeout: 10s
      retries: 15
  shlink-web:
    image: shlinkio/shlink-web-client
    environment:
      - SERVICE_FQDN_SHLINKWEB_8080
      - 'SHLINK_SERVER_API_KEY=${SERVICE_BASE64_SHLINKAPIKEY}'
      - 'SHLINK_SERVER_URL=${SERVICE_FQDN_SHLINK}'
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://127.0.0.1:8080'
      interval: 2s
      timeout: 10s
      retries: 15
```
