### DISCUSSION TITLE
Can't find the admin panel => bad documentation, or bug

### DISCUSSION THREAD

**Discussion by NeilSCGH** [shlinkio/shlink#2402] [Help wanted]
### Shlink version

latest

### PHP version

probably latest

### How do you serve Shlink

Docker image

### Database engine

SQLite

### Database version

probably latest

### Current behavior

I cannot find the admin panel of shlink, to add shortened urls...

When I go to the root of the server `http://ip:port`, The server returns a 404 error:
![Image](https://github.com/user-attachments/assets/988ab925-78ee-41ab-8064-28424bb8c097)

I run it in docker via
```
services:
    shlink:
        container_name: my_shlink
        ports:
            - 8086:8080
        environment:
            - DEFAULT_DOMAIN=mydomain.com
            - IS_HTTPS_ENABLED=true
        image: shlinkio/shlink:stable
```

Where is the admin panel? The [documentation](https://shlink.io/documentation/install-docker-image/) doesn't give the admin panel path 

Note: IS_HTTPS_ENABLED is set to true, but when visiting `https://ip:port` I have ERR_SSL_PROTOCOL_ERROR.

### Expected behavior

Visiting the server root should give the admin panel, or redirect to it

### Minimum steps to reproduce

1. Run shlink via docker compose

```
services:
    shlink:
        container_name: my_shlink
        ports:
            - 8086:8080
        environment:
            - DEFAULT_DOMAIN=mydomain.com
            - IS_HTTPS_ENABLED=true
        image: shlinkio/shlink:stable
```

1. Visit the server
