### DISCUSSION TITLE
Help wanted - Docker Setup

### DISCUSSION THREAD

**Discussion by franco640** [shlinkio/shlink#2404] [Help wanted]
### Shlink version

4.46

### PHP version

8.4.5

### How do you serve Shlink

Docker image

### Database engine

MySQL

### Database version

8.0

### Summary

I'm unable to get this to work. It has been very frustrating and I hope someone can help. 

**#### Docker Compose File #####**

```
version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD= # My Password
      - MYSQL_DATABASE=shlink
      - MYSQL_USER=shlink_user
      - MYSQL_PASSWORD=# My Password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
    networks:
      shlink_net:
        ipv4_address: 172.19.0.5

  shlink:
    image: ghcr.io/shlinkio/shlink:stable  # ✅ Using GHCR instead of Docker Hub
    container_name: shlink
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DEFAULT_DOMAIN= # My Domain (This is valid and working on DNS)
      - IS_HTTPS_ENABLED=true
      - GEOLITE_LICENSE_KEY= # My key 
      - DB_DRIVER=mysql
      - DB_USER=shlink_user
      - DB_PASSWORD=# My Password
      - DB_NAME=shlink
      - DB_HOST=mysql
      - DB_PORT=3306
      - SHELL_VERBOSITY=3
    command: ["./bin/rr", "serve", "-c", "config/roadrunner/.rr.yml"]
    ports:
      - "8080:8080"
    networks:
      shlink_net:
        ipv4_address: 172.19.0.3

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - DOMAIN= # My Domain (This is valid and working on DNS)
    networks:
      shlink_net:
        ipv4_address: 172.19.0.4

  shlink-web:
    image: shlinkio/shlink-web-client:latest
    container_name: shlink-web
    restart: unless-stopped
    environment:
      - SHLINK_SERVER_URL= # My Domain (This is valid and working on DNS)
      - SHLINK_SERVER_API_KEY= # My key   05172ad5-********
      - SHLINK_SERVER_NAME= # Shlink
    ports:
      - "8081:80"  # ✅ Maps host 8081 -> container 80
    networks:
      shlink_net:
        ipv4_address: 172.19.0.2

networks:
  shlink_net:
    name: shlink_net
    driver: bridge
    ipam:
      config:
        - subnet: "172.19.0.0/16"  # Subnet for the custom network

volumes:
  mysql_data:
  caddy_data:
  caddy_config:
```

**###### My Caddy file for reverse proxy #######**

```
{
  # (Optional) Use the staging CA while testing to avoid rate limits.
  # Remove or comment this out for production.
  # I had to use this because I used up my allowance 
  acme_ca https://acme-staging-v02.api.letsencrypt.org/directory 
}
http:// {
        redir https://{host}{uri}
}

# Shlink API Reverse Proxy
devdocker.****** {
        reverse_proxy shlink:8080
        header {
                Access-Control-Allow-Origin "https://shlink-web.devdocker.*****"
                Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS"
                Access-Control-Allow-Headers "Origin, Content-Type, Accept, Authorization"
        }
}

# Shlink Web UI Reverse Proxy
shlink-web.******* {
        reverse_proxy shlink-web:8080
        header {
                Access-Control-Allow-Origin "https://devdocker.******"
                Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS"
                Access-Control-Allow-Headers "Origin, Content-Type, Accept, Authorization"
        }
}

```

Checking these both works 

`docker exec -it shlink-web /bin/sh -c "curl http://shlink:8080/rest/v3/health"`

![Screenshot 2025-03-26 at 08 40 02](https://github.com/user-attachments/assets/e019c6bf-711a-4a4c-b8b2-01747c05e85a)

`docker exec -it shlink-web /bin/sh -c "curl http://shlink-web:8080/rest/v3/health`

![Screenshot 2025-03-26 at 08 39 41](https://github.com/user-attachments/assets/67c0b108-fafc-4243-8b5c-90fcae12ae76)

`docker exec -it shlink curl -I http://localhost:8080/rest/v3/health`

![Screenshot 2025-03-26 at 08 43 50](https://github.com/user-attachments/assets/9e201f86-71db-4aca-8689-c975c94cb239)

Other Info that might help..

**#### Docker PS #####**

![Screenshot 2025-03-26 at 08 13 27](https://github.com/user-attachments/assets/72813e22-1cf1-4201-8588-8938ec4572aa)

**#### Docker Network inspect shlink_net #####**

![Screenshot 2025-03-26 at 08 16 11](https://github.com/user-attachments/assets/043cfc04-2cd7-41f2-8c64-95483fcd3dd3)

**#### I  have it configured like so #####**

![Screenshot 2025-03-26 at 07 53 48](https://github.com/user-attachments/assets/9936341b-6dc3-4ecb-b832-2cb8a8ff403c)

but I still get 

![Screenshot 2025-03-26 at 07 53 33](https://github.com/user-attachments/assets/6eab8535-95da-4c9d-b7cd-a8648aa7d9c5)

FYI 

These pages do show up 

![Screenshot 2025-03-26 at 09 54 37](https://github.com/user-attachments/assets/43293ccb-6cf6-4f89-a58b-eaddee4cc840)

![Screenshot 2025-03-26 at 09 55 03](https://github.com/user-attachments/assets/932d4c43-d18c-4dd3-912b-356499e3beb7)
