### DISCUSSION TITLE
Messages not published in RabbitMQ

### DISCUSSION THREAD

**Discussion by thoughtsunificator** [shlinkio/shlink#2443] [Help wanted] [answered]
### Shlink version

4.4.6

### PHP version

8.4.5

### How do you serve Shlink

Docker image

### Database engine

MySQL

### Database version

mariadb:10.8

### Summary

I am unable to get shlink to publish updates to rabbitmq. 

``docker-compose.yml``

```yaml
version: "3"
services:
  rabbitmq:
    healthcheck: 
        test: ["CMD-SHELL", "rabbitmqctl status"]
    image: rabbitmq
  shlink:
    image: shlinkio/shlink:stable
    restart: always
    environment:
      - TZ="Europe/Paris"
      - DEFAULT_DOMAIN=foo
      - IS_HTTPS_ENABLED=true
      - DB_DRIVER=maria
      - DB_USER=shlink
      - DB_NAME=shlink
      - DB_PASSWORD=shlink
      - DB_HOST=database
      - SHELL_VERBOSITY=3
      - RABBITMQ_ENABLED=true
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
    depends_on:
      database:
        condition: service_started
      rabbitmq:
        condition: service_healthy
        restart: true
    ports:
      - 8080:8080
    
  shlink_web:
    image: shlinkio/shlink-web-client:stable
    restart: always
    environment:
      - tz="europe/paris"
    depends_on:
      - database
      - rabbitmq
    ports:
      - 8188:8080

  database:
    image: mariadb:10.8
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=shlink
      - MARIADB_DATABASE=shlink
      - MARIADB_USER=shlink
      - MARIADB_PASSWORD=shlink
    volumes:
      - ./data/db_data:/var/lib/mysql
```

shlink logs:

```
shlink-1  | Initializing database if needed... [Running "/usr/local/bin/php bin/cli db:create"]   RUN  '/usr/local/bin/php' 'bin/cli' 'db:create'
shlink-1  |   OUT  
shlink-1  |   OUT   [OK] Database already exists. Run "db:migrate" command to make sure it is up to
shlink-1  |   OUT        date.                                                                     
shlink-1  |   OUT  
shlink-1  |   OUT  
shlink-1  |   RES  Command ran successfully
shlink-1  |  Success!
shlink-1  | Updating database... [Running "/usr/local/bin/php bin/cli db:migrate"]   RUN  '/usr/local/bin/php' 'bin/cli' 'db:migrate'
shlink-1  |   OUT  Migrating database...
shlink-1  |   OUT  
shlink-1  |   ERR    RUN  '/usr/local/bin/php' 'vendor/doctrine/migrations/bin/doctrine-migrations.php' 'migrations:migrate' '--no-interaction'
shlink-1  |   ERR    OUT  
shlink-1  |   ERR    OUT   [WARNING] You have 18 previously executed migrations in the database that are  
shlink-1  |   ERR    OUT             not registered migrations.                                           
shlink-1  |   ERR    OUT  
shlink-1  |   ERR    OUT   >> 2023-12-23 12:54:43 (ShlinkMigrations\Version20160819142757)
shlink-1  |   ERR    OUT   >> 2023-12-23 12:54:44 (ShlinkMigrations\Version20160820191203)
shlink-1  |   ERR    OUT   >> 2023-12-23 12:54:44 (ShlinkMigrations\Version20171021093246)
shlink-1  |   ERR    OUT   >> 2023-12-23 12:54:44 (ShlinkMigrations\Version20171022064541)
shlink-1  |   ERR    OUT   >> 2023-12-23 12:54:44 (ShlinkMigrations\Version20180801183328)
shlink-1  |   ERR    OUT   >> 2023-12-23 12:54:44 (ShlinkMigrations\Version20180913205455)
shlink-1  |   ERR    OUT   >> 2023-12-23 12:54:44 (ShlinkMigrations\Version20180915110857)
shlink-1  |   ERR    OUT   >> 2023-12-23 12:54:44 (ShlinkMigrations\Version20181020060559)
shlink-1  |   ERR    OUT   >> 2023-12-23 12:54:44 (ShlinkMigrations\Version20181020065148)
shlink-1  |   ERR    OUT   >> 2023-12-23 12:54:44 (ShlinkMigrations\Version20181110175521)
shlink-1  |   ERR    OUT   >> 2023-12-23 12:54:44 (ShlinkMigrations\Version20190824075137)
shlink-1  |   ERR    OUT   >> 2023-12-23 12:54:44 (ShlinkMigrations\Version20190930165521)
shlink-1  |   ERR    OUT   >> 2023-12-23 12:54:44 (ShlinkMigrations\Version20191001201532)
shlink-1  |   ERR    OUT   >> 2023-12-23 12:54:44 (ShlinkMigrations\Version20191020074522)
shlink-1  |   ERR    OUT   >> 2023-12-23 12:54:44 (ShlinkMigrations\Version20200110182849)
shlink-1  |   ERR    OUT   >> 2023-12-23 12:54:44 (ShlinkMigrations\Version20210118153932)
shlink-1  |   ERR    OUT   >> 2023-12-23 12:54:44 (ShlinkMigrations\Version20220110113313)
shlink-1  |   ERR    OUT   >> 2024-06-08 19:13:49 (ShlinkMigrations\Version20230103105343)
shlink-1  |   ERR    OUT  
shlink-1  |   ERR    OUT   [OK] Successfully migrated to version: ShlinkMigrations\Version20250215100756  
shlink-1  |   ERR    OUT  
shlink-1  |   ERR    OUT  
shlink-1  |   ERR    OUT  
shlink-1  |   ERR    RES  Command ran successfully
shlink-1  |   ERR  
shlink-1  |   OUT  
shlink-1  |   OUT   [OK] Database properly migrated!                                               
shlink-1  |   OUT  
shlink-1  |   OUT  
shlink-1  |   RES  Command ran successfully
shlink-1  |  Success!
shlink-1  | Generating proxies... [Running "/usr/local/bin/php bin/doctrine orm:generate-proxies"]   RUN  '/usr/local/bin/php' 'bin/doctrine' 'orm:generate-proxies'
shlink-1  |   ERR   Processing entity "Shlinkio\Shlink\Core\RedirectRule\Entity\ShortUrlRedirectRule"
shlink-1  |   ERR   Processing entity "Shlinkio\Shlink\Core\Visit\Entity\OrphanVisitsCount"
shlink-1  |   ERR   Processing entity "Shlinkio\Shlink\Core\Visit\Entity\Visit"
shlink-1  |   ERR   Processing entity "Shlinkio\Shlink\Core\Visit\Entity\VisitLocation"
shlink-1  |   ERR   Processing entity "Shlinkio\Shlink\Core\Geolocation\Entity\GeolocationDbUpdate"
shlink-1  |   ERR   Processing entity "Shlinkio\Shlink\Core\Visit\Entity\ShortUrlVisitsCount"
shlink-1  |   ERR   Processing entity "Shlinkio\Shlink\Core\Domain\Entity\Domain"
shlink-1  |   ERR   Processing entity "Shlinkio\Shlink\Core\RedirectRule\Entity\RedirectCondition"
shlink-1  |   ERR   Processing entity "Shlinkio\Shlink\Core\Tag\Entity\Tag"
shlink-1  |   ERR   Processing entity "Shlinkio\Shlink\Core\ShortUrl\Entity\ShortUrl"
shlink-1  |   ERR   Processing entity "Shlinkio\Shlink\Rest\Entity\ApiKeyRole"
shlink-1  |   ERR   Processing entity "Shlinkio\Shlink\Rest\Entity\ApiKey"
shlink-1  |   ERR  
shlink-1  |   ERR   Proxy classes generated to "/etc/shlink/data/proxies"
shlink-1  |   ERR  
shlink-1  |   RES  Command ran successfully
shlink-1  |  Success!
shlink-1  | Clearing entities cache... [Running "/usr/local/bin/php bin/doctrine orm:clear-cache:metadata"]   RUN  '/usr/local/bin/php' 'bin/doctrine' 'orm:clear-cache:metadata'
shlink-1  |   ERR  
shlink-1  |   ERR   // Clearing all Metadata cache entries                                         
shlink-1  |   ERR  
shlink-1  |   ERR   [OK] Successfully deleted cache entries.                                       
shlink-1  |   ERR  
shlink-1  |   ERR  
shlink-1  |   RES  Command ran successfully
shlink-1  |  Success!
shlink-1  | {"level":"debug","ts":1749111112000033647,"logger":"rpc","msg":"plugin was started","address":"tcp://127.0.0.1:6001","list of the plugins with RPC methods:":["lock","informer","jobs","app","resetter"]}
shlink-1  | 2025-06-05T08:11:52+0000    DEBUG   jobs            initializing driver     {"pipeline": "shlink", "driver": "memory"}
shlink-1  | 2025-06-05T08:11:52+0000    DEBUG   jobs            driver ready    {"pipeline": "shlink", "driver": "memory", "start": "2025-06-05T08:11:52+0000", "elapsed": 1}
shlink-1  | {"level":"debug","ts":1749111112002128173,"logger":"memory","msg":"pipeline was started","driver":"memory","pipeline":"shlink","start":"2025-06-05 08:11:52.002118241 +0000 UTC","elapsed":"11.26µs"}
shlink-1  | [INFO] RoadRunner server started; version: 2024.3.5, buildtime: 2025-02-27T17:24:29+0000
shlink-1  | [INFO] sdnotify: not notified
shlink-1  | 2025-06-05T08:11:56+0000    INFO    server          [2025-06-05T08:11:56.580563+00:00] [8d2b72e2-45ba-4fd6-8ae8-1d9e12a8f27e] Access.INFO - OPTIONS /rest/v3/short-urls 204 0
shlink-1  | 2025-06-05T08:11:56+0000    DEBUG   jobs            job was pushed successfully     {"ID": "a3c24120-4302-4cfe-b307-c70e0d634414", "pipeline": "shlink", "driver": "memory", "start": "2025-06-05T08:11:56+0000", "elapsed": 0}
shlink-1  | {"level":"debug","ts":1749111116768738982,"logger":"memory","msg":"message pushed to the priority queue","current":1,"limit":10}
shlink-1  | 2025-06-05T08:11:56+0000    DEBUG   jobs            job processing was started      {"ID": "a3c24120-4302-4cfe-b307-c70e0d634414", "start": "2025-06-05T08:11:52+0000", "elapsed": 4626}
shlink-1  | 2025-06-05T08:11:56+0000    INFO    server          [2025-06-05T08:11:56.772631+00:00] [fd0370f3-1946-40ed-babc-86bc8292e98a] Access.INFO - POST /rest/v3/short-urls 200 367
shlink-1  | 2025-06-05T08:11:56+0000    DEBUG   jobs            job was processed successfully  {"ID": "a3c24120-4302-4cfe-b307-c70e0d634414", "start": "2025-06-05T08:11:52+0000", "elapsed": 4717}
```

As you can see, there is no relevant logs as to what is going on (even with the DEBUG verbosity on) with the RabbitMQ publishing. We are not even told whether RabbitMQ is enabled...

```sh
[foo@bar shlink]$ docker compose exec -it rabbitmq rabbitmq-diagnostics list_exchanges
Listing exchanges for vhost / ...
name    type
amq.match       headers
amq.rabbitmq.trace      topic
amq.topic       topic
amq.headers     headers
amq.fanout      fanout
amq.direct      direct
        direct
```

```sh
[foo@bar shlink]$ docker compose exec -it rabbitmq rabbitmq-diagnostics list_queues
Timeout: 60.0 seconds ...
Listing queues for vhost / .
```
