### ISSUE TITLE
Docker Compose & CaddyFile

### ISSUE THREAD

**Issue by yodaphone** [shlinkio/shlink#1070]
I use caddy as my reverse proxy to my docker. if someone is interested to deploy it using docker compose and use Caddy, you can try this

Docker Compose file: (You can add more variables as you need. I use a mariadb server thats running on another VM which i use for all my projects)

```
#shlink
version: '3'

services:
 shlink:
    image: shlinkio/shlink:stable
    container_name: my_shlink
    ports:
      - 8080:8080
    environment:
      SHORT_DOMAIN_HOST: 'url.foo.com'
      SHORT_DOMAIN_SCHEMA: 'https'
      GEOLITE_LICENSE_KEY: 'XXXXXXXX'
      DB_DRIVER: 'maria'
      DB_NAME: 'shlink'
      DB_USER: 'shlink'
      DB_PASSWORD: 'x12345'
      DB_HOST: '192.168.1.254'
      DB_PORT: '3306'
```

Caddyfile - The top few lines are useful. You can uncomment the "acme_ca" to staging & test before you ask for the real one. this may help you as you dont want to hit the cert request limits. Caddy is very easy to use 

```
{
    # email to use on Let's Encrypt
    email johndoe@emai.com

    # Uncomment for debug
    #acme_ca https://acme-staging-v02.api.letsencrypt.org/directory
    debug
}

url.foo.com {
    reverse_proxy http://192.168.1.74:8080
}
```
