### ISSUE TITLE
Could not connect to this Shlink server

### ISSUE THREAD

**Issue by yodaphone** [shlinkio/shlink#1088]
#### How Shlink is set-up

* Shlink Version: 2.6.2
* PHP Version: Docker
* How do you serve Shlink: Docker image
* Database engine used: MariaDB

#### Summary

I run shlink in a docker container. when i go to app.shlink.io from my home network, i get

"Oops! Could not connect to this Shlink server.

Make sure you have internet connection, and the server is properly configured and on-line."

I run the docker behind a Caddy Reverse Proxy

**_HOWEVER - If i access app.shlink.io from outside my home network it works fine_**

My browser console says

`xhr.js:175 GET https://wow.swamy39.com/rest/v2/health net::ERR_CONNECTION_TIMED_OUT`

It was working fine a day back but now i get this error. No changes were made on my end

Docker compose

```
 shlink:
    image: shlinkio/shlink:stable
    container_name: shlink
    ports:
      - 8090:8080
    environment:
      SHORT_DOMAIN_HOST: 'wow.swamy39.com'
      SHORT_DOMAIN_SCHEMA: 'https'
      GEOLITE_LICENSE_KEY: 'XXXXX'
      DB_DRIVER: 'maria'
      DB_NAME: 'shlink'
      DB_USER: 'shlink'
      DB_PASSWORD: 'XXXXXX'
      DB_HOST: '192.168.11.67'
      DB_PORT: '3306'
      ANONYMIZE_REMOTE_ADDR: 'false'
    restart: always

```

Caddy 

```
wow.swamy39.com {
    reverse_proxy http://192.168.11.74:8090
}
```
