### ISSUE TITLE
Example Compose Stack that includes the Web UI?

### ISSUE THREAD

**Issue by YouveGotMeowxy** [shlinkio/shlink#1290]
Can anyone tell me what's wrong with this stack? All I get is a white page when trying to visit the web ui:

```
version: "3.8"

services:

    shlink:
        hostname: shlink
        image: shlinkio/shlink:latest
        environment:
            TZ: ${TZ}
            PUID: 1000
            PGID: 1000
            DEFAULT_DOMAIN: 'shlink.mydomain.com'
            IS_HTTPS_ENABLED: 'true'
            GEOLITE_LICENSE_KEY: 'redacted'
            DB_DRIVER: 'mysql'
            DB_HOST: 'mysql'
            DB_USER: 'shlink'
            DB_PASSWORD: 'redacted'
        networks:
            - odb
        deploy:
          mode: replicated
          replicas: 1
          placement:
            constraints:
              - node.labels.Main == true
          restart_policy:
            condition: any
 
    shlink-web-client:
        hostname: shlink-web-client
        image: shlinkio/shlink-web-client:latest
        environment:
            TZ: ${TZ}
            PUID: 1000
            PGID: 1000
        depends_on:
            - shlink
        ports:
            - 8990:80
        networks:
            - odb
        deploy:
          mode: replicated
          replicas: 1
          placement:
            constraints:
              - node.labels.Main== true
          restart_policy:
            condition: any

networks:
  odb:
    external: true
    name: db
```

It's connecting and filling the db, so the db connection isn't the issue.

TIA
