### ISSUE TITLE
createdb fails on timescaledb, but doctrine orm commands work.

### ISSUE THREAD

**Issue by jhogendorn** [shlinkio/shlink#1734]
#### How Shlink is set up

* Shlink Version: 3.5.1
* How do you serve: Docker image
* Database engine used: TimescaleDB (PostgreSQL)

#### Summary

createdb command fails when you start the container against a non existent or empty database.

#### Current behavior

when you start the container, it will run createdb. it will create the db if there is none, but it will not build any structure inside it. it seems to fail early. then the migrations fail because there are no initial tables to act upon.

#### Expected behavior

I expect a fresh container against a fresh db to work on timescaledb, which is just an extension of postgresql. The differences are more schemas and functions that are visible to the dbal. there are also extra types available.

#### How to reproduce

docker-compose.yml

```
version: '3.3'
services:
  shlink:
    container_name: shlink
    restart: always
    environment:
      - SHORT_DOMAIN_HOST=mydomain
      - SHORT_DOMAIN_SCHEMA=https
      - DB_DRIVER=postgres
      - DB_NAME=shlink
      - DB_USER=admin
      - DB_PASSWORD=foobar
      - DB_HOST=timescale
      - DB_PORT=5432
    image: shlinkio/shlink:3.5.1
  db:
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: foobar
    image: timescale/timescaledb:latest-pg14
    container_name: timescale
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data

```

bring up timescaledb, then bring up shlink. shlink will fail to create the db.

`docker-compose run --entrypoint sh shlink` and running the relevant doctrine commands to create and init the db will work fine and let you then run migrations.
