### ISSUE TITLE
Issue after updating from v3.5.4 to v3.6.0 using docker image

### ISSUE THREAD

**Issue by gabriel-lando** [shlinkio/shlink#1794]
#### How Shlink is set up

* Shlink Version: 3.6.0
* PHP Version: Not sure :(
* How do you serve Shlink: Docker image (tag: `stable`)
* Database engine used: MySQL (Docker image `mysql:latest`)

#### Summary

After upgrading to latest version, everything stopped working. When I tried to access any URL, I was receiving `400 Bad Request` error.
I use Watchtower weekly to keep my images always up to date and I was using `shlink:stable` docker image.
This is the docker-compose YAML file I'm currently using:

```yaml
version: "3"

services:
  shlink:
    image: shlinkio/shlink:stable
    pull_policy: always
    container_name: shlink
    restart: unless-stopped
    tty: true
    stdin_open: true
    external_links:
      - mysql:mysql
    environment:
      IS_HTTPS_ENABLED: "true"
      DEFAULT_DOMAIN: ${SHLINK_DOMAIN}
      DB_DRIVER: ${SHLINK_DB_DRIVER}
      DB_NAME: ${SHLINK_DB_NAME}
      DB_USER: ${SHLINK_DB_USER}
      DB_PASSWORD: ${SHLINK_DB_PASSWORD}
      DB_HOST: ${SHLINK_DB_HOST}
      GEOLITE_LICENSE_KEY: ${SHLINK_GEOLITE_KEY}
      DEFAULT_INVALID_SHORT_URL_REDIRECT: ${SHLINK_INVALID_REDIRECT}
      DEFAULT_REGULAR_404_REDIRECT: ${SHLINK_404_REDIRECT}
      DEFAULT_BASE_URL_REDIRECT: ${SHLINK_URL_REDIRECT}
    networks:
      - swag-network

networks:
  swag-network:
    name: swag

```

I tried a lot of times different ways to fix it, including testing different tags of the docker image. the one that is working for me is `3.6.0-openswoole`. Found [here](https://github.com/shlinkio/shlink/releases/tag/v3.6.0).

Apparently, it seems an issue during the migration to the new docker runtime.

Follow the Docker logs after starting the `stable` tag:

```
2023-05-29T19:42:55.587040095Z Initializing database if needed... Success!
2023-05-29T19:42:56.257996950Z Updating database... Success!
2023-05-29T19:42:56.462195804Z Generating proxies... Success!
2023-05-29T19:42:56.622473012Z Clearing entities cache... Success!
2023-05-29T19:42:59.443052926Z Downloading GeoLite2 db file... Success!
2023-05-29T19:43:02.003282865Z DBG | ts=1685389382000112000 logger=rpc msg=plugin was started address=tcp://127.0.0.1:6001 list of the plugins with RPC methods:=["jobs","informer","lock","app","resetter"] 
2023-05-29T19:43:02.007814525Z DBG | ts=1685389382007457800 logger=jobs msg=driver ready pipeline=shlink driver=memory start=1685389382006990600 elapsed=0.000463939 
2023-05-29T19:43:02.008035023Z DBG | ts=1685389382007619000 logger=memory msg=pipeline was started driver=memory pipeline=shlink start=2023-05-29 19:43:02.007607254 +0000 UTC elapsed=27.213µs 
2023-05-29T19:43:02.115126210Z 2023-05-29T19:43:02+0000	DEBUG	server      	worker is allocated	{"pid": 37, "internal_event_name": "EventWorkerConstruct"}
2023-05-29T19:43:02.120645209Z 2023-05-29T19:43:02+0000	DEBUG	server      	worker is allocated	{"pid": 35, "internal_event_name": "EventWorkerConstruct"}
2023-05-29T19:43:02.134300150Z 2023-05-29T19:43:02+0000	DEBUG	server      	worker is allocated	{"pid": 36, "internal_event_name": "EventWorkerConstruct"}
2023-05-29T19:43:02.140990934Z 2023-05-29T19:43:02+0000	DEBUG	server      	worker is allocated	{"pid": 38, "internal_event_name": "EventWorkerConstruct"}
2023-05-29T19:43:02.246398144Z 2023-05-29T19:43:02+0000	DEBUG	server      	worker is allocated	{"pid": 40, "internal_event_name": "EventWorkerConstruct"}
2023-05-29T19:43:02.246436777Z 2023-05-29T19:43:02+0000	DEBUG	server      	worker is allocated	{"pid": 44, "internal_event_name": "EventWorkerConstruct"}
2023-05-29T19:43:02.246446226Z 2023-05-29T19:43:02+0000	DEBUG	server      	worker is allocated	{"pid": 43, "internal_event_name": "EventWorkerConstruct"}
2023-05-29T19:43:02.248997149Z 2023-05-29T19:43:02+0000	DEBUG	server      	worker is allocated	{"pid": 45, "internal_event_name": "EventWorkerConstruct"}
2023-05-29T19:43:02.251224562Z [INFO] RoadRunner server started; version: 2023.1.3, buildtime: 2023-05-11T12:32:12+0000
```

#### Current behavior

Right now, I can use my instance with `3.6.0-openswoole` tag. But I noticed that this runner is being deprecated soon.

#### Expected behavior

I expect that it works with the new runner :D

#### How to reproduce

I'm not sure. I'm using the same instance for a long long time (about 1.5 years). In the past I had to update my env vars during an upgrade, but since then I never touched anything. Watchtower always could handle the updates for me.

If I return to any tag that uses Roadrunner runtime, the issue starts happening again.

Obs: I never tried to rollback to a previous version.

**Comment by acelaya** [comment]
> When I tried to access any URL, I was receiving 400 Bad Request error.

It would be good to know what is the response body for those 400 errors, because according to your logs, the server started successfully, but it is not registering any incoming request, which makes me think there's something in front of Shlink returning those errors.

**Comment by gabriel-lando** [comment]
Ohh that's exactly the response body :)

![Screenshot](https://github.com/shlinkio/shlink/assets/18423120/de938967-d882-4926-977d-aabad231218c)

And I'm pretty sure that this response came from the shlink service, because if I turn it off, I receive the default NGINX 502 error (I'm using the Linuxserver's SWAG docker with NGINX as the reverse proxy for this service)

One (maybe important) information that I forgot to mention:
- I have 2 domains.
- My `DEFAULT_DOMAIN` env var value is `exam.ple`.
- The domain `exam.ple` is configured on my Cloudflare account redirecting every request to `https://url.example.com`
  - So, a call to `https://exam.ple/docs` is being redirected on Cloudflare to `https://url.example.com/docs`
- The `https://url.example.com` points to the shlink container using SWAG+NGINX
- shlink redirects to the final URL
- Using `openswoole` runtime, it aways worked :D

**Comment by acelaya** [comment]
Can you also share the request and response heades? Nginx can return 400s when configured as reverse proxy and sending too big headers.

Also, please check nginx logs, as the reason for the error will be most likely there. Perhaps openswoole accepts a bigger request by defaault a d roadrunner is rejecting it.

**Comment by gabriel-lando** [comment]
Of course.

I did a cleanup in the nginx logs. After trying to access a URL, this was the content of the `access.log` file:

```
10.0.0.1 - - [30/May/2023:01:16:42 -0300] "GET /docs HTTP/2.0" 400 15 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 Edg/113.0.1774.57"
10.0.0.1 - - [30/May/2023:01:16:42 -0300] "GET /favicon.ico HTTP/2.0" 400 15 "https://url.example.com/docs" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 Edg/113.0.1774.57"
``` 

The `error.log` keeps empty (no error log was generated).

Regarding the request and response headers, these are all headers:

![ScreenshotHeaders](https://github.com/shlinkio/shlink/assets/18423120/778ed8f4-ed50-4759-bd7f-b86337072af0)

**Comment by acelaya** [comment]
Can you try to put together a reproducible scenario via docker compose, with nginx as reverse proxy and Shlink 3.6 with roadrunner?

Also, sharing your nginx config would be helpful.

**Comment by gabriel-lando** [comment]
I will create a new environment to try to reproduce the issue at the end of the day :) while, follow my nginx config:

```
## Version 2021/05/18
# make sure that your dns has a cname set for <container_name> and that your <container_name> container is not using a base url

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name url.*;

    set $upstream_app shlink;
    set $upstream_port 8080;
    set $upstream_proto http;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    location / {
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;

        proxy_pass $upstream_proto://$upstream_app:$upstream_port;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
```

**Comment by gabriel-lando** [comment]
Hi, I could reproduce the issue in a new (fresh) environment.
Follow all the config files used:

Docker-Compose YAML:

```yaml
version: "3"

services:
  shlink:
    image: shlinkio/shlink:stable
    pull_policy: always
    container_name: shlink
    restart: unless-stopped
    tty: true
    stdin_open: true
    depends_on:
      - mysql
    external_links:
      - mysql:mysql
    environment:
      IS_HTTPS_ENABLED: "true"
      DEFAULT_DOMAIN: ${SHLINK_DOMAIN}
      DB_DRIVER: ${SHLINK_DB_DRIVER}
      DB_NAME: ${SHLINK_DB_NAME}
      DB_USER: ${SHLINK_DB_USER}
      DB_PASSWORD: ${SHLINK_DB_PASSWORD}
      DB_HOST: ${SHLINK_DB_HOST}
      GEOLITE_LICENSE_KEY: ${SHLINK_GEOLITE_KEY}
      DEFAULT_INVALID_SHORT_URL_REDIRECT: ${SHLINK_INVALID_REDIRECT}
      DEFAULT_REGULAR_404_REDIRECT: ${SHLINK_404_REDIRECT}
      DEFAULT_BASE_URL_REDIRECT: ${SHLINK_URL_REDIRECT}
    networks:
      - swag-network

  swag:
    image: "ghcr.io/linuxserver/swag:latest"
    pull_policy: always
    container_name: swag
    restart: unless-stopped
    tty: true
    stdin_open: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${SWAG_PATH}:/config
    environment:
      PUID: 1000
      PGID: 1000
      TZ: "America/Sao_Paulo"
      URL: ${SWAG_DOMAIN}
      EXTRA_DOMAINS: ${SWAG_EXTRA_DOMAINS}
      VALIDATION: "dns"
      DNSPLUGIN: "cloudflare"
      EMAIL: ${SWAG_EMAIL}
      STAGING: "false"
    cap_add:
      - NET_ADMIN
    networks:
      - swag-network

  mysql:
    image: mysql:latest
    pull_policy: always
    container_name: mysql
    restart: unless-stopped
    tty: true
    stdin_open: true
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ${MYSQL_PATH}:/var/lib/mysql
    networks:
      - swag-network

networks:
  swag-network:
    name: swag
```

.env file with the environment variables:

```
# Swag variables
SWAG_PATH="/data/swag"
SWAG_DOMAIN="example.com"
SWAG_EXTRA_DOMAINS="*.example.com"
SWAG_EMAIL="example@example.com"

# MySQL variables
MYSQL_PATH="/data/mysql"
MYSQL_DATABASE="shlink"
MYSQL_PASSWORD="example-password"

# Shlink variables
SHLINK_DOMAIN="exam.ple"
SHLINK_DB_DRIVER="mysql"
SHLINK_DB_NAME="shlink"
SHLINK_DB_USER="root"
SHLINK_DB_PASSWORD="example-password"
SHLINK_DB_HOST="mysql"
SHLINK_GEOLITE_KEY="example-key"
SHLINK_INVALID_REDIRECT="https://app.shlink.io/"
SHLINK_404_REDIRECT="https://app.shlink.io/"
SHLINK_URL_REDIRECT="https://app.shlink.io/"
```

NGINX configuration file (`url.subdomain.conf`):

```
## Version 2021/05/18
# make sure that your dns has a cname set for <container_name> and that your <container_name> container is not using a base url

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name url.*;

    set $upstream_app shlink;
    set $upstream_port 8080;
    set $upstream_proto http;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    location / {
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
```

Other configurations I did:
- I turned off the main instance of the shlink (running in another VM)
- I configured my `pihole` instance to point the CNAME Record `url.example.com` to the VM name, so I didn't have to change it in my domain settings (I usually use a Cloudflare tunnel to allow external access).
- I added my Cloudflare API Key to the swag config file in `/data/swag/dns-conf/cloudflare.ini`.

To test, I tried to open `https://url.example.com` in my browser, it should forward me to the `https://app.shlink.io/` webpage, but I received the `400 Bad Request` instead.

Obs: it's important to mention that I used my real domain during this test.

**Comment by acelaya** [comment]
I think the issue is somewhere in `swag`s configuration.

I put together a simple example using plain nginx as reverse proxy, over HTTP, and everything works just fine.

```yaml
version: "3"

services:
  shlink:
    image: shlinkio/shlink:3.6.0
    container_name: shlink
    restart: unless-stopped
    tty: true
    stdin_open: true
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      IS_HTTPS_ENABLED: "true"
      DEFAULT_DOMAIN: ${SHLINK_DOMAIN}
      DB_DRIVER: ${SHLINK_DB_DRIVER}
      DB_NAME: ${SHLINK_DB_NAME}
      DB_USER: ${SHLINK_DB_USER}
      DB_PASSWORD: ${SHLINK_DB_PASSWORD}
      DB_HOST: ${SHLINK_DB_HOST}
      GEOLITE_LICENSE_KEY: ${SHLINK_GEOLITE_KEY}
      DEFAULT_INVALID_SHORT_URL_REDIRECT: ${SHLINK_INVALID_REDIRECT}
      DEFAULT_REGULAR_404_REDIRECT: ${SHLINK_404_REDIRECT}
      DEFAULT_BASE_URL_REDIRECT: ${SHLINK_URL_REDIRECT}

  swag:
    image: "nginx:1.25"
    container_name: swag
    restart: unless-stopped
    tty: true
    stdin_open: true
    ports:
      - "8888:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    cap_add:
      - NET_ADMIN
    links:
      - shlink

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    tty: true
    stdin_open: true
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
```

```
# MySQL variables
MYSQL_PATH="/data/mysql"
MYSQL_DATABASE="shlink"
MYSQL_PASSWORD="example-password"

# Shlink variables
SHLINK_DOMAIN="exam.ple"
SHLINK_DB_DRIVER="mysql"
SHLINK_DB_NAME="shlink"
SHLINK_DB_USER="root"
SHLINK_DB_PASSWORD="example-password"
SHLINK_DB_HOST="mysql"
SHLINK_GEOLITE_KEY="example-key"
SHLINK_INVALID_REDIRECT="https://app.shlink.io/"
SHLINK_404_REDIRECT="https://app.shlink.io/"
SHLINK_URL_REDIRECT="https://app.shlink.io/"
```

```
server {
    listen 80 default_server;

    client_max_body_size 0;

    location / {
        proxy_pass http://shlink:8080;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
```

What I find very weird is that you are not getting any error logged in your nginx when it is returning a 400 response, because nginx always logs errors with INFO level.

Make sure there's nothing else preventing nginx logs, as that's the only way to find the root cause.
