### ISSUE TITLE
I cannot start the container while pointing to an external MySQL DB

### ISSUE THREAD

**Issue by maxacarvalho** [shlinkio/shlink#1850]
### Shlink version

3.6.3

### PHP version

8.1

### How do you serve Shlink

RoadRunner Docker image

### Database engine

MySQL

### Database version

8

### Current behavior

Hi,

I have a local dev environment using Docker compose. Pretty standard stuff:

```yaml
version: '3'
services:
  web:
    build: docker/web
    depends_on:
      - myapp
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "$PWD/docker/web/nginx.conf:/etc/nginx/nginx.conf"
      - "$PWD/docker/web/templates:/etc/nginx/http.d"
      - "$PWD/docker/web/tls:/etc/nginx/tls"
      # Applications
      - "$PWD/src/myapp/public:/app/myapp/public"
      - "$PWD/src/myapp/storage/app:/app/myapp/storage/app"
    tty: true
    networks:
      myapp:
        aliases:
          - myapp.test
          - nks.test

  myapp:
    build: docker/php
    depends_on:
      - mysql
    tty: true
    volumes:
      - "$PWD/src/myapp:/app/myapp"
    working_dir: /app/myapp
    environment:
      - DEVDOCK_DB_HOST=${DEVDOCK_DB_HOST:-mysql}
      - DEVDOCK_DB_PORT=${DEVDOCK_DB_PORT:-3306}
      - DEVDOCK_DB_DATABASE=${DEVDOCK_DB_DATABASE:-myapp}
      - DEVDOCK_DB_USERNAME=${DEVDOCK_DB_USERNAME:-root}
      - DEVDOCK_DB_PASSWORD=${DEVDOCK_DB_PASSWORD:-secret}
      - DEVDOCK_MYSQL_ROOT_PASSWORD=${DEVDOCK_DB_PASSWORD:-secret}
      - DEVDOCK_IDE_KEY=${DEVDOCK_IDE_KEY:-docker}
      - DEVDOCK_XDEBUG_CLIENT_HOST=${DEVDOCK_XDEBUG_CLIENT_HOST:-host.docker.internal}
      - DEVDOCK_XDEBUG_MODE=${DEVDOCK_XDEBUG_MODE:-off}
    networks:
      - myapp

  mysql:
    build:
      context: docker/mysql
      dockerfile: Dockerfile
    ports:
      - "${DEVDOCK_FWD_DB_PORT:-3306}:3306"
    volumes:
      - "$PWD/docker/mysql/config-file.cnf:/etc/mysql/conf.d/config-file.cnf"
      - "$PWD/docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
      - "myapp_data_mysql:/var/lib/mysql"
    networks:
      - myapp
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping" ]
    environment:
      - MYSQL_ROOT_PASSWORD=${DEVDOCK_DB_PASSWORD:-secret}
      - MYSQL_DATABASE=${DEVDOCK_DB_DATABASE:-myapp}
      - MYSQL_USER=${DEVDOCK_DB_USERNAME:-myapp}
      - MYSQL_PASSWORD=${DEVDOCK_DB_PASSWORD:-secret}

  shlink:
    image: shlinkio/shlink:3.6.3
    depends_on:
      - mysql
    networks:
      - mynetwork
    environment:
      - DEFAULT_DOMAIN=shlink.test
      - GEOLITE_LICENSE_KEY=${DEVDOCK_GEOLITE_LICENSE_KEY:-}
      - INITIAL_API_KEY=${DEVDOCK_INITIAL_API_KEY:-}
      - DB_DRIVER=${DEVDOCK_SHLINK_DB_DRIVER:-mysql}
      - DB_NAME=${DEVDOCK_SHLINK_DB_NAME:-shlink}
      - DB_USER=${DEVDOCK_SHLINK_DB_USER:-myapp}
      - DB_PASSWORD=${DEVDOCK_SHLINK_DB_PASSWORD:-secret}
      - DB_HOST=${DEVDOCK_SHLINK_DB_HOST:-mysql}
      - DB_PORT=${DEVDOCK_SHLINK_DB_PORT:-3306}

networks:
  mynetwork:
    driver: "bridge"

volumes:
  myapp_data_redis:
    driver: local
  myapp_data_mysql:
    driver: local
```

Every time I try to start the stack the Shlink container won't boot up.  
Checking the Docker compose logs I can see the following:
```
myapp-shlink-1  | Initializing database if needed...
myapp-shlink-1  |
myapp-shlink-1  |
myapp-shlink-1  |  [ERROR] Error generating database.. Run this command with -vvv to see specific
myapp-shlink-1  |          error info.
myapp-shlink-1  |
myapp-shlink-1  |
```

If I try to run the container with something like `docker compose run shlink sh`, the first time I get some errors like this:
```
handle_serve_command: Function call error:
	got initial serve error from the Vertex *http.Plugin, stopping execution, error: static_pool_allocate_workers: WorkerAllocate:
	goridge_frame_receive: validation failed on the message sent to STDOUT, see: https://roadrunner.dev/docs/known-issues-stdout-crc/2.x/en, invalid message:
Fatal error: Uncaught PDOException: SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction in /etc/shlink/vendor/doctrine/dbal/src/Driver/PDO/Statement.php:121
Stack trace:
```

Once I try again it works. From that point on I can start the stack normally.

I already tried to create the shlink DB before hand, the table structure I mean, still won't work.

Any advice?

Thanks!

### Expected behavior

I believe I should be able to start the container successfully.

### How to reproduce

I believe the docker-compose file described above should be enough.
