### ISSUE TITLE
Oops! Could not connect to this Shlink server.

### ISSUE THREAD

**Issue by modem7** [shlinkio/shlink#1957]
### Shlink version

3.7.1

### PHP version

docker

### How do you serve Shlink

Other (explain in summary)

### Database engine

MariaDB

### Database version

linuxserver/mariadb

### Current behavior

![image](https://github.com/shlinkio/shlink/assets/4349962/963bfc8c-649b-4359-b073-d6eee05b288e)

### Expected behavior

For the server to be seen. 

`https://shorturl.mydomain.com/rest/v2/health` returns:
`{"status":"pass","version":"3.7.1","links":{"about":"https://shlink.io","project":"https://github.com/shlinkio/shlink"}}`

### How to reproduce

```yaml
  shlink:
    image: 'shlinkio/shlink:stable'
    container_name: Shlink
    environment:
        - DB_HOST=shlinkdb
        - DB_PASSWORD=$SHLINK_DB_PWD
        - DB_USER=$SHLINK_DB_USER
        - DB_DRIVER=maria
        - GEOLITE_LICENSE_KEY=$SHLINK_MAXIMIND
        - AUTO_RESOLVE_TITLES=true
        - TIMEZONE=$TZ
        - IS_HTTPS_ENABLED=true
        - DEFAULT_DOMAIN=$DOMAINNAME
        - INITIAL_API_KEY=$SHLINK_API_KEY
    logging:
      driver: "local"
      options:
        max-size: 10m
        max-file: "3"
    networks:
      pihole:
        ipv4_address: '172.22.0.115'
      isolated:
    labels:
      - autoheal=true
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.shlink-rtr.entrypoints=https"
      - "traefik.http.routers.shlink-rtr.rule=Host(`shorturl.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.shlink-rtr.middlewares=chain-no-auth@file" # No Authentication
      # - "traefik.http.routers.shlink-rtr.middlewares=chain-basic-auth@file" # Basic Authentication
      # - "traefik.http.routers.shlink-rtr.middlewares=chain-oauth-admins@file" # Keycloak
      ## HTTP Services
      - "traefik.http.routers.shlink-rtr.service=shlink-svc"
      - "traefik.http.services.shlink-svc.loadbalancer.server.port=8080"
      ## Homepage
      # - homepage.name=Snapp
      # - homepage.group=Other
      # - homepage.icon=https://raw.githubusercontent.com/dullage/flatnotes/master/flatnotes/src/assets/android-chrome-512x512.png
      # - homepage.href=https://snapp.$DOMAINNAME
    restart: always
    depends_on:
      - shlinkdb

  shlink-web-client:
    image: shlinkio/shlink-web-client
    container_name: Shlink-Web
    environment:
        - SHLINK_SERVER_API_KEY=$SHLINK_API_KEY
        - SHLINK_SERVER_URL=https://shorturl.$DOMAINNAME
    ports:
        - 57010:80
    networks:
      pihole:
        ipv4_address: '172.22.0.111'
      isolated:
    labels:
      - autoheal=true
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.shlinkweb-rtr.entrypoints=https"
      - "traefik.http.routers.shlinkweb-rtr.rule=Host(`shorturlweb.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.shlinkweb-rtr.middlewares=chain-no-auth@file" # No Authentication
      # - "traefik.http.routers.shlinkweb-rtr.middlewares=chain-basic-auth@file" # Basic Authentication
      # - "traefik.http.routers.shlinkweb-rtr.middlewares=chain-oauth-admins@file" # Keycloak
      ## HTTP Services
      - "traefik.http.routers.shlinkweb-rtr.service=shlinkweb-svc"
      - "traefik.http.services.shlinkweb-svc.loadbalancer.server.port=80"
      ## Homepage
      # - homepage.name=Snapp
      # - homepage.group=Other
      # - homepage.icon=https://raw.githubusercontent.com/dullage/flatnotes/master/flatnotes/src/assets/android-chrome-512x512.png
      # - homepage.href=https://snapp.$DOMAINNAME
    restart: always

  shlinkdb:
    image: linuxserver/mariadb
    container_name: Shlink-DB
    networks:
      - isolated
    expose:
      - "3306"
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - MYSQL_DATABASE=$SHLINK_DATABASE
      - MYSQL_USER=$SHLINK_DB_USER
      - MYSQL_PASSWORD=$SHLINK_DB_PWD
      - MYSQL_ROOT_PASSWORD=$SHLINK_DB_ROOT_PASSWORD
    logging:
      driver: "local"
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - $USERDIR/Shlink/DB:/config
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 30s
      timeout: 1s
      retries: 5
    labels:
      - backup
      - autoheal=true
    restart: always
```
