### ISSUE TITLE
Error mouting volume

### ISSUE THREAD

**Issue by tiritibambix** [shlinkio/shlink#1990]
### Shlink version

v3.7.3

### PHP version

7.4.33

### How do you serve Shlink

Self-hosted nginx

### Database engine

MariaDB

### Database version

10.8

### Current behavior

Creates `server.json`as a folder.

### Expected behavior

Should create `server.json`as a file.

### How to reproduce

Hi, I've been using slink for a moment using docker and I love it. I used portainer to deploy it.

Tonight, I was updating shlink using latest images when I got an error message:
```
error mounting "[...]/Files/Shlink/servers.json" to rootfs at "/usr/share/nginx/html/servers.json": mount [...]/Files/Shlink/servers.json:/usr/share/nginx/html/servers.json (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? 
```

To be honest, I'm not really knowledgeable enough to understand why it started creating a folder instead of the .json file, and now shlink won't launch because of it. I've tried restoring a backup, but that didn't work. I even attempted to create the .json file myself, but it resulted in a lot of errors.

Any ideas on how I can fix this? I would really appreciate your help.

Thanks you.

P.S.: here is my docker-compose if it can help.

```
version: "3"

services:
  shlink:
    image: shlinkio/shlink:stable
    restart: unless-stopped
    container_name: shlink-backend
    environment:
      - TZ="Europe/Paris"
      - DEFAULT_DOMAIN=my.domain.tld
      - IS_HTTPS_ENABLED=true
      - GEOLITE_LICENSE_KEY=blablabla
      - DB_DRIVER=maria
      - DB_USER=shlink
      - DB_NAME=shlink
      - DB_PASSWORD=omgpassword
      - DB_HOST=database
    depends_on:
      - database
    ports:
      - 8987:8080

  database:
    image: mariadb:10.8
    restart: unless-stopped
    container_name: shlink-database
    environment:
      - MARIADB_ROOT_PASSWORD=omgpassword
      - MARIADB_DATABASE=shlink
      - MARIADB_USER=shlink
      - MARIADB_PASSWORD=omgpassword
    volumes:
      - [...]/Files/Shlink/db:/var/lib/mysql

  shlink-web-client:
    image: shlinkio/shlink-web-client
    restart: unless-stopped
    container_name: shlink-gui
    volumes:
      - [...]/Files/Shlink/servers.json:/usr/share/nginx/html/servers.json
    depends_on:
      - shlink
    ports:
      - 8986:80
```
