### ISSUE TITLE
Error 502 Bad Gateway with NPM (nginx proxy manager)

### ISSUE THREAD

**Issue by PolGZ** [shlinkio/shlink#2028]
### Shlink version

latest docker

### PHP version

latest on docker

### How do you serve Shlink

Docker image

### Database engine

MariaDB

### Database version

mariadb:latest

### Current behavior

I get

```
502 Bad Gateway 
---
openresty
```

error when trying to access a shortened URL (that I made accessing the `https://app.shlink.io/` connecting to my internal IP address 192.168.1.10:8081 and the CLI generated API KEY.

As well as when trying to access the url.

Docker compose file:

```
version: '3'

services:
  shlink:
    image: shlinkio/shlink:stable
    restart: unless-stopped
    environment:
      - TZ="Europe/Madrid"
      - SHELL_VERBOSITY=3
      - DEFAULT_DOMAIN=link.domain.com
      - IS_HTTPS_ENABLED=true
      - DB_DRIVER=maria
      - DB_USER=shlink
      - DB_NAME=shlink
      - DB_PASSWORD=mdbpassword
      - DB_HOST=sh_database
    depends_on:
      - sh_database
    ports:
      - 8081:8080

  sh_database:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=mdbpassword
      - MARIADB_DATABASE=shlink
      - MARIADB_USER=shlink
      - MARIADB_PASSWORD=mdpassword
    volumes:
      - /home/polgz/dockers/shlink/db_data:/var/lib/mysql
```

On nginx proxy manager (docker:latest):

```
proxy_buffer_size          128k;
proxy_buffers              4 256k;
proxy_busy_buffers_size    256k;

location / {
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_pass http://localhost:8081;
    proxy_read_timeout 90s;
}
```

Router and firewall port open.

I used a subdomain because the `domain.com` is already assigned in NPM to the port of my Hugo website server.

### Expected behavior

Being able to access it from the https URL

### How to reproduce

Using docker shlink and docker NPM with shown configs.
