### ISSUE TITLE
Not able to connect to the MySQL DB

### ISSUE THREAD

**Issue by TataQueen** [shlinkio/shlink#2197]
### Shlink version

4.2.0

### PHP version

included with the docker image

### How do you serve Shlink

Docker image

### Database engine

MySQL

### Database version

8.0.39 (docker image)

### Current behavior

I can ping both machines from eachother with the bridged adapter between them

```
my_shlink    |   ERR  In Driver.php line 33:
my_shlink    |   ERR
my_shlink    |   ERR    [PDOException (1045)]
my_shlink    |   ERR    SQLSTATE[HY000] [1045] Access denied for user 'shlinkuser'@'172.27.0.3' (us
my_shlink    |   ERR    ing password: YES)
```

### Expected behavior

For it to connect and not bootloop on this error. For some reason it can't log in to the MySQL user, but when I connect manually to it it's possible

### Minimum steps to reproduce

This is my `docker-compose.yml`

```
version: '3'
services:
  my_shlink:
    image: shlinkio/shlink:stable
    container_name: my_shlink
    environment:
      - SHELL_VERBOSITY=3
      - DEFAULT_DOMAIN=gothgf.link
      - IS_HTTPS_ENABLED=true
      - DB_DRIVER=mysql
      - DB_NAME=shlink
      - DB_USER=shlinkuser
      - DB_PASSWORD='verysecretpassword'
      - DB_HOST=mysql
    ports:
      - "127.0.0.1:8080:8080"
    restart: unless-stopped
    networks:
      - my_bridge

  mysql:
    image: mysql:8.0
    container_name: mysql_shlink
    environment:
      MYSQL_ROOT_PASSWORD: 'theverysecretrootpassword'
      MYSQL_DATABASE: shlink
      MYSQL_USER: shlinkuser
      MYSQL_PASSWORD: 'verysecretpassword'
    ports:
      - "3306:3306"
    restart: unless-stopped
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_bridge

networks:
  my_bridge:
    driver: bridge

volumes:
  mysql_data:
    driver: local
```

When I do `docker-compose up -d` the container restarts in a loop and when I check the logs it says 
```
my_shlink    |   ERR  In Driver.php line 33:
my_shlink    |   ERR
my_shlink    |   ERR    [PDOException (1045)]
my_shlink    |   ERR    SQLSTATE[HY000] [1045] Access denied for user 'shlinkuser'@'172.27.0.3' (us
my_shlink    |   ERR    ing password: YES)
```
Thank you for your time and patience 💞
