### ISSUE TITLE
Fatal error: Declaration of Cake\Chronos\Chronos::createFromTimestamp must be compatible with DateTimeImmutable::createFromTimestamp

### ISSUE THREAD

**Issue by ilgigante77** [shlinkio/shlink#2322]
### Shlink version

4.4.0

### PHP version

	8.4.2

### How do you serve Shlink

Docker image

### Database engine

SQLite

### Database version

???

### Current behavior

Fatal error: Declaration of Cake\Chronos\Chronos::createFromTimestamp(int $timestamp, DateTimeZone|string|null $timezone = null): static must be compatible with DateTimeImmutable::createFromTimestamp(int|float $timestamp): static in /etc/shlink/vendor/cakephp/chronos/src/Chronos.php on line 743

### Expected behavior

normal start

### Minimum steps to reproduce

```
services:
    shlink:
        image: shlinkio/shlink:stable-roadrunner
        environment:
            - GEOLITE_LICENSE_KEY=xxxx
            - IS_HTTPS_ENABLED=true
            - DEFAULT_DOMAIN=xxxxx
            - INITIAL_API_KEY=xxxx
        ports:
            - '8088:8080'
        container_name: shlink
        restart: always
        volumes:
          - shlink_data:/etc/shlink
        healthcheck:
          test: "curl -k --fail http://127.0.0.1:8080/EpoXj || exit 1"
          interval: 1m30s
          timeout: 10s
          retries: 3
          start_period: 5s
    shlink-web-client:
        image: shlinkio/shlink-web-client
        environment:
            - SHLINK_SERVER_API_KEY=xxxxx
            - 'SHLINK_SERVER_URL=http://dun-srv-tools:8088'
        restart: always
        ports:
            - '8089:8080'
        container_name: shlink-web-client
        healthcheck:
          test: "curl -k --fail http://127.0.0.1:8080 || exit 1"
          interval: 1m30s
          timeout: 10s
          retries: 3
          start_period: 5s

volumes:
  shlink_data:
```
