### ISSUE TITLE
Add Tag to existing link sometimes results in 504

### ISSUE THREAD

**Issue by filou01** [shlinkio/shlink#2444]
### Shlink version

4.4.6

### PHP version

4.4.6

### How do you serve Shlink

Docker image

### Database engine

MicrosoftSQL

### Database version

-

### Current behavior

Creating a short link and adding TAGs to it usually works. But there is a timepoint after that it´s not possible to add TAGs to existing links any more. The Result is 504 Gateway Time-out after 30 seconds.
Restarting the Container resolves this issue.
I cannot find any events while this occours in the Log of the container. I´ve also tried it with SHELL_VERBOSITY=3 
What i´ve found out, that every time a TAG is added successfully a lock file within data/locks/ is created but not removed anymore.

It´s a single container deployment without redis or something similar behind.

### Expected behavior

TAGs should can be added without any issue

### Minimum steps to reproduce

As the error is not from the beginning, but after some days of a running service, i just have to wait and then try to add some tags. Most times the first tag can be added but then it stalls.

**Comment by filou01** [comment]
This is definitly a locking problem. When the problem occurs, and i delete all the files in /etc/shlink/data/locks, the problem is resolved for the moment until the next time the locking problem occurs.
But definitly there is no cleanup with the lock files, thats why the problem occur

**Comment by filou01** [comment]
Current workaround: use redis
With redis the locks are deleted successfully, it seems as the problem just occurs when the locks are created as files within the filesystem

**Comment by acelaya** [comment]
Thanks @filou01.

Just wanted to confirm I've seen this and all provided information is very useful on trying to understand what the root cause for the lock files to not be deleted is.

I'm currently focus on other parts of the Shlink ecosystem and won't be able to work on this for a while, but it's not being ignored.

Thanks for your patience and understanding.

**Comment by acelaya** [comment]
I'm wondering. Are you running your containers in some particular infra, system or with some configuration that applies filesystem restrictions?

**Comment by acelaya** [comment]
Just to make sure, I tested this with MicrosoftSQL, rather than SQLite (although it didn't seem that was related), and everything worked fine following provided steps.

I used this docker compose config file:

```yml
services:
    shlink:
      image: shlinkio/shlink:4.4.6
      ports:
          - "9999:8080"
      links:
        - db
      environment:
        INITIAL_API_KEY: foobar
        DB_DRIVER: mssql
        DB_USER: sa
        DB_PASSWORD: "Passw0rd!"
        DB_HOST: db
        SHELL_VERBOSITY: 3
    
    db:
      image: mcr.microsoft.com/mssql/server:2022-latest
      ports:
        - "1439:1433"
      environment:
        ACCEPT_EULA: Y
        SA_PASSWORD: "Passw0rd!"
```

I suspect there's something odd with the filesystem which is not allowing lockfiles to be released, but I can't fix it if I can't reproduce it.

I'm going to close this for now as not reproducible. I'm happy to reopen if anyone else experiences this and can provide more details.
