### ISSUE TITLE
worker_id must be less than task_worker_num

### ISSUE THREAD

**Issue by leolivier** [shlinkio/shlink#851]
#### How Shlink is set-up

* Shlink Version: 2.3.0
* PHP Version: docker image one
* How do you serve Shlink: Docker image (stable image on Raspberry Pi, arm/v7)
* Database engine used: SQLite 

#### Summary

When accessing to a generated short link, I get a 500 error.

#### Current behavior
When accessing to a generated link, I get a 500 error
 and the log shows the following exception

```
[2020-10-03T10:43:40.941875+00:00] [NULL] Shlink.ERROR - ErrorException: Swoole\Server::task(): worker_id must be less than task_worker_num[16] in /etc/shlink/vendor/shlinkio/shlink-event-dispatcher/src/Listener/AsyncEventListener.php:22
Stack trace:
#0 [internal function]: Laminas\Stratigility\Middleware\ErrorHandler->Laminas\Stratigility\Middleware\{closure}(2, 'Swoole\\Server::...', '/etc/shlink/ven...', 22, Array)
#1 /etc/shlink/vendor/shlinkio/shlink-event-dispatcher/src/Listener/AsyncEventListener.php(22): Swoole\Server->task(Object(Shlinkio\Shlink\EventDispatcher\Listener\EventListenerTask))
#2 /etc/shlink/vendor/phly/phly-event-dispatcher/src/EventDispatcher.php(39): Shlinkio\Shlink\EventDispatcher\Listener\AsyncEventListener->__invoke(Object(Shlinkio\Shlink\Core\EventDispatcher\ShortUrlVisited))
#3 /etc/shlink/module/Core/src/Service/VisitsTracker.php(48): Phly\EventDispatcher\EventDispatcher->dispatch(Object(Shlinkio\Shlink\Core\EventDispatcher\ShortUrlVisited))
#4 /etc/shlink/module/Core/src/Action/AbstractTrackingAction.php(58): Shlinkio\Shlink\Core\Service\VisitsTracker->track(Object(Shlinkio\Shlink\Core\Entity\ShortUrl), Object(Shlinkio\Shlink\Core\Model\Visitor))
#5 /etc/shlink/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(47): Shlinkio\Shlink\Core\Action\AbstractTrackingAction->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#6 /etc/shlink/vendor/laminas/laminas-stratigility/src/Next.php(61): Mezzio\Middleware\LazyLoadingMiddleware->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#7 /etc/shlink/vendor/akrabat/ip-address-middleware/src/IpAddress.php(91): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#8 /etc/shlink/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(47): RKA\Middleware\IpAddress->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#9 /etc/shlink/vendor/laminas/laminas-stratigility/src/Next.php(61): Mezzio\Middleware\LazyLoadingMiddleware->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#10 /etc/shlink/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(84): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#11 /etc/shlink/vendor/mezzio/mezzio-router/src/Route.php(101): Laminas\Stratigility\MiddlewarePipe->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#12 /etc/shlink/vendor/mezzio/mezzio-router/src/RouteResult.php(111): Mezzio\Router\Route->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#13 /etc/shlink/vendor/mezzio/mezzio-router/src/Middleware/DispatchMiddleware.php(36): Mezzio\Router\RouteResult->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#14 /etc/shlink/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(47): Mezzio\Router\Middleware\DispatchMiddleware->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#15 /etc/shlink/vendor/laminas/laminas-stratigility/src/Next.php(61): Mezzio\Middleware\LazyLoadingMiddleware->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#16 /etc/shlink/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(84): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#17 /etc/shlink/vendor/laminas/laminas-stratigility/src/Next.php(61): Laminas\Stratigility\MiddlewarePipe->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#18 /etc/shlink/vendor/laminas/laminas-stratigility/src/Middleware/PathMiddlewareDecorator.php(48): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#19 /etc/shlink/vendor/laminas/laminas-stratigility/src/Next.php(61): Laminas\Stratigility\Middleware\PathMiddlewareDecorator->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#20 /etc/shlink/vendor/laminas/laminas-stratigility/src/Next.php(54): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#21 /etc/shlink/vendor/mezzio/mezzio-router/src/Middleware/ImplicitHeadMiddleware.php(85): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#22 /etc/shlink/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(47): Mezzio\Router\Middleware\ImplicitHeadMiddleware->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#23 /etc/shlink/vendor/laminas/laminas-stratigility/src/Next.php(61): Mezzio\Middleware\LazyLoadingMiddleware->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#24 /etc/shlink/vendor/mezzio/mezzio-router/src/Middleware/RouteMiddleware.php(57): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#25 /etc/shlink/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(47): Mezzio\Router\Middleware\RouteMiddleware->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#26 /etc/shlink/vendor/laminas/laminas-stratigility/src/Next.php(61): Mezzio\Middleware\LazyLoadingMiddleware->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#27 /etc/shlink/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(84): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#28 /etc/shlink/vendor/laminas/laminas-stratigility/src/Next.php(61): Laminas\Stratigility\MiddlewarePipe->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#29 /etc/shlink/vendor/laminas/laminas-stratigility/src/Next.php(54): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#30 /etc/shlink/vendor/shlinkio/shlink-common/src/Middleware/CloseDbConnectionMiddleware.php(27): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#31 /etc/shlink/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(47): Shlinkio\Shlink\Common\Middleware\CloseDbConnectionMiddleware->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#32 /etc/shlink/vendor/laminas/laminas-stratigility/src/Next.php(61): Mezzio\Middleware\LazyLoadingMiddleware->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#33 /etc/shlink/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(84): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#34 /etc/shlink/vendor/laminas/laminas-stratigility/src/Next.php(61): Laminas\Stratigility\MiddlewarePipe->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#35 /etc/shlink/vendor/laminas/laminas-stratigility/src/Middleware/PathMiddlewareDecorator.php(48): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#36 /etc/shlink/vendor/laminas/laminas-stratigility/src/Next.php(61): Laminas\Stratigility\Middleware\PathMiddlewareDecorator->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#37 /etc/shlink/vendor/laminas/laminas-stratigility/src/Next.php(54): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#38 /etc/shlink/vendor/laminas/laminas-stratigility/src/Middleware/ErrorHandler.php(144): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#39 /etc/shlink/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(47): Laminas\Stratigility\Middleware\ErrorHandler->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#40 /etc/shlink/vendor/laminas/laminas-stratigility/src/Next.php(61): Mezzio\Middleware\LazyLoadingMiddleware->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#41 /etc/shlink/vendor/mezzio/mezzio-helpers/src/ContentLengthMiddleware.php(32): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#42 /etc/shlink/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(47): Mezzio\Helper\ContentLengthMiddleware->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#43 /etc/shlink/vendor/laminas/laminas-stratigility/src/Next.php(61): Mezzio\Middleware\LazyLoadingMiddleware->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#44 /etc/shlink/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(84): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#45 /etc/shlink/vendor/laminas/laminas-stratigility/src/Next.php(61): Laminas\Stratigility\MiddlewarePipe->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#46 /etc/shlink/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(84): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#47 /etc/shlink/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(73): Laminas\Stratigility\MiddlewarePipe->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\EmptyPipelineHandler))
#48 /etc/shlink/vendor/mezzio/mezzio-swoole/src/SwooleRequestHandlerRunner.php(244): Laminas\Stratigility\MiddlewarePipe->handle(Object(Laminas\Diactoros\ServerRequest))
#49 {main}
[2020-10-03T10:43:40.947553+00:00] [NULL] Access.ERROR - 192.168.0.8 - - "GET /shlink/FSDpx HTTP/1.1" 500 875

```

#### Expected behavior

No exception

#### How to reproduce

Here is the docker-compose file I use and start with docker-compose up -d. It's using traefik for the routing but I don't think it's linked.
```
networks:
  shlink-network:
    name: shlink-network
  traefik-network:
    name: traefik-network
services:
  shlink:
    container_name: shlink
    depends_on:
    - traefik
    environment:
      BASE_PATH: /shlink
      GEOLITE_LICENSE_KEY: MGinbtU64pzfFdUt
      SHORT_DOMAIN_HOST: ${DOMAIN}
      SHORT_DOMAIN_SCHEMA: https
    image: shlinkio/shlink:stable
    labels:
      traefik.docker.network: shlink-network
      traefik.enable: 'true'
      traefik.http.routers.shlink.entrypoints: web
      traefik.http.routers.shlink.rule: PathPrefix(`/shlink/`) || Path(`/shlink`)
      traefik.http.routers.shlink.service: shlink
      traefik.http.services.shlink.loadbalancer.server.port: 8080
    networks:
      shlink-network: {}
    restart: unless-stopped
  traefik:
    container_name: traefik
    environment:
    - TRAEFIK_API=true
    - TRAEFIK_DASHBOARD=true
    - TRAEFIK_PROVIDERS_DOCKER=true
    - TRAEFIK_PROVIDERS_DOCKER_ENDPOINT=unix:///var/run/docker.sock
    - TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT=false
    - TRAEFIK_LOG_LEVEL=DEBUG
    - TRAEFIK_GLOBAL_SENDANONYMOUSUSAGE=false
    - TRAEFIK_ENTRYPOINTS_WEB_ADDRESS=:80
    - TRAEFIK_ENTRYPOINTS_WEBSECURE_ADDRESS=:443
    image: traefik:latest
    labels:
      traefik.enable: 'true'
      traefik.http.middlewares.dashboard-addslash.redirectregex.regex: ^(.*)/dashboard$$
      traefik.http.middlewares.dashboard-addslash.redirectregex.replacement: $${1}/dashboard/
      traefik.http.routers.api.entrypoints: web
      traefik.http.routers.api.middlewares: dashboard-addslash@docker
      traefik.http.routers.api.rule: PathPrefix(`/api/`) || PathPrefix(`/dashboard/`) || Path(`/api`) || Path(`/dashboard`)
      traefik.http.routers.api.service: api@internal
    networks:
      shlink-network: {}
      traefik-network: {}
    ports:
    - 80:80
    - 443:443
    restart: unless-stopped
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro

```
Then I create a link with e.g.:
```
$ docker exec -it shlink shlink short-url:generate https://google.com      
Processed long URL: https://google.com
Generated short URL: https://<mydomain>/shlink/zSPry
```

And when I access the short link, I get the error (whatever the target)
