### ISSUE TITLE
404 (regular redirect) when accessing to short url in the browser

### ISSUE THREAD

**Issue by leolivier** [shlinkio/shlink#855]
#### How Shlink is set-up

  *  Shlink Version: 2.3.0
  * PHP Version: docker image one
  *  How do you serve Shlink: Docker image (stable image on Raspberry Pi, arm/v7)
  *  Database engine used: SQLite

#### Summary
When I use a short URL in the browser (same with wget) I have a 404...

#### Current behavior
I installed shlink with the docker version using the following envt to be able to see what kind of 404 I get:
```
           environment:
              SHORT_DOMAIN_HOST: "${DOMAIN}"
              GEOLITE_LICENSE_KEY: 'MGinbtU64pzfFdUt'
              BASE_PATH: '/shlink'
              SHORT_DOMAIN_SCHEMA: 'https'
              INVALID_SHORT_URL_REDIRECT_TO: 'https://shlink.io'
              REGULAR_404_REDIRECT_TO: 'https://github.io'
              BASE_URL_REDIRECT_TO: 'https://gitlab.com'
```
Then I generate a short link whith the following commands and it seems to work properly:
```
cloudathome@cloudathome:~/Services $ docker exec -it shlink shlink short-url:generate https://www.google.com
Processed long URL: https://www.google.com
Generated short URL: https://<mydomain>/shlink/avHtW
cloudathome@cloudathome:~/Services $ docker exec -it shlink shlink short-url:list
+------------+-----------------------------------------------+------------------------+---------------------------+--------------+
| Short code | Short URL                                     | Long URL               | Date created              | Visits count |
+------------+-----------------------------------------------+------------------------+---------------------------+--------------+
| avHtW      | https://<mydomain>/shlink/avHtW               | https://www.google.com | 2020-10-11T15:01:30+00:00 | 0            |
+------------+-------------------------------------------- Page 1 of 1 ---------------+---------------------------+--------------+

[OK] Short URLs properly listed                                                                                        
```
But when I access the short link in my browser, I am redirected to github (due to the REGULAR_404_REDIRECT_TO: 'https://github.io' in my config)

#### Expected behavior

Should be directed to google

#### How to reproduce

See above
