### ISSUE TITLE
502 Bad Gateway for short link with long original link

### ISSUE THREAD

**Issue by nathanielread** [shlinkio/shlink#957]
I'm receiving 502 Bad Gateway errors when going to links from very long original_links. 

I regularly have links I'd like to share that are 4000+ characters. I've tried increasing the size of the original_url field in postgres to 6000 and text.

At first I was receiving errors with the long links and googled that the database column wasn't large enough.

These are the commands I used for those attempts:
```
ALTER TABLE short_urls
ALTER COLUMN original_url TYPE text;

ALTER TABLE short_urls
ALTER COLUMN original_url TYPE character varying(6000);
```

The logs show this when I go to the short url for these long original urls:
[2021-01-08T14:34:10.578682+00:00] [c5384510-f2a9-4c4c-8689-f9d192f7e600] Access.INFO - 98.192.4.240 - - "GET /rYpIO HTTP/1.1" 302 -,
[2021-01-08T14:34:10.709336+00:00] [c5384510-f2a9-4c4c-8689-f9d192f7e600] Shlink.NOTICE - Task #1 has finished processing

I'm setup in docker, running behind jwilder nginx-proxy. I've removed the domains from the docker-compose:
```
version: '3'

services:
  shlink:
    container_name: shlink
    image: shlinkio/shlink
    expose:
      - 8080
    environment:
      SHORT_DOMAIN_HOST: domain.com
      SHORT_DOMAIN_SCHEMA: http
      VIRTUAL_PORT: 8080
      VIRTUAL_PROTO: http
      VIRTUAL_HOST: domain.com
      LETSENCRYPT_HOST: domain.com
      LETSENCRYPT_EMAIL: me@domain.com
      HOSTNAME: shlink.local
      DB_DRIVER: postgres
      DB_USER: postgres
      DB_PASSWORD: shlink
      DB_HOST: shlink_db_postgres
      VALIDATE_URLS: "true"
      REDIS_SERVERS: tcp://shlink_redis:6379
      ANONYMIZE_REMOTE_ADDR: "false"
      GEOLITE_LICENSE_KEY: [KEY]
    depends_on:
      - shlink_db_postgres
      - shlink_redis
    networks:
      nginxproxy_service_network:

  shlink_web_client:
    container_name: shlink_web_client
    image: shlinkio/shlink-web-client
    expose:
      - 80
    volumes:
      - ./servers.json:/usr/share/nginx/html/servers.json
    environment:
      VIRTUAL_PORT: 80
      VIRTUAL_PROTO: http
      VIRTUAL_HOST: otherdomain.com
      LETSENCRYPT_HOST: otherdomain.com
      LETSENCRYPT_EMAIL: me@domain.com
      HOSTNAME: shlink-web-client.local
    networks:
      nginxproxy_service_network:

  shlink_db_postgres:
    container_name: shlink_db_postgres
    image: postgres:alpine
    volumes:
      - ./data/infra/database_pg:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: pw
      POSTGRES_DB: shlink
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      nginxproxy_service_network:

  shlink_redis:
    container_name: shlink_redis
    image: redis:alpine
    networks:
      nginxproxy_service_network:

networks:
  nginxproxy_service_network:
    external: true
```

Do I need to modify something else to get this to work? Or where can I look to figure out more about this problem?
